apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      containers:
      - name: alpine-job
        image: alpine:3.14
        command:
         - "/bin/sh"
         - "-c"
         - "/bin/echo Hello world from Pod $(hostname) at $(date)"
      restartPolicy: Never
