apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypv
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: slow    