apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rpod
  name: rpod
spec:
  containers:
  - image: nginx
    name: rpod
    resources:
      limits:
        cpu: 0.2
        memory: 100Mi  
      requests:
        cpu: 0.2
        memory: 100Mi  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
