apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master-volume
  labels:
    type: local
spec:
  storageClassName: master-manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/redis-master"
