apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      volumes:
      - name: data-master
        persistentVolumeClaim:
          claimName: redis-master-claim
      - name: data
        persistentVolumeClaim:
          claimName: redis-data-claim
      containers:
      - image: redis:alpine
        name: redis
        volumeMounts:
        - mountPath: "/mnt/data"
          name: data
        - mountPath: "mnt/master"
          name: data-master    
        resources: 
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"          
status: {}
