apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-master-claim
spec:
  storageClassName: master-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

