apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-volume
  labels:
    type: local
spec:
  storageClassName: data-manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/redis-data"
