apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: run-as-username
  name: run-as-username
spec:
  containers:
  - image: busybox
    name: run-as-username
    resources:
      requests:
        cpu: 0.2
        memory: 100Mi  
      limits:
        cpu: 0.3
        memory: 150Mi  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
